version: "3"
services:
  quotesvc:
    image: jmreif/quotesvc
    ports:
      - 8088:8088
    # networks:
    #   - dockerdemo
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  edgesvc:
    image: jmreif/edgesvc
    ports:
      - "8086:8086"
    depends_on:
      - quotesvc
    # networks:
    #   - dockerdemo
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
# networks:
#   dockerdemo:
